#pragma once

#include <WinSDKVer.h>
//#define WINAPI_FAMILY WINAPI_FAMILY_DESKTOP_APP

//_WIN32_WINNT_WIN6
#define WINVER _WIN32_WINNT_WINXP //_WIN32_WINNT_WIN7
#define _WIN32_WINNT _WIN32_WINNT_WINXP //_WIN32_WINNT_WIN7
